#!/bin/sh
set -eu
DIR="/home/jb/dev/eclipse-update-site"

mvn clean package
mkdir -p "$DIR"
rm -rf "$DIR/easysync"
cp -a site/target/repository "$DIR/easysync"

git -C "$DIR" add -A
git -C "$DIR" commit -m "update"
git -C "$DIR" push

echo "repository updated"
